apiVersion: v1
kind: Service

metadata:
  name: clinic-4-service
  labels:
    app: clinic
    clinic: clinic-4

spec:
  selector:
    app: clinic
    clinic: clinic-4

  ports:
  - name: http
    protocol: TCP
    port: 8007
    targetPort: 8007

  type: ClusterIP
