apiVersion: v1
kind: Service

metadata:
  name: scheduler-service
  labels:
    app: scheduler

spec:
  selector:
    app: scheduler

  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  - name: metrics
    protocol: TCP
    port: 9000
    targetPort: 9000

  type: NodePort
