apiVersion: v1
kind: Service

metadata:
  name: medical-worker-service
  labels:
    app: medical-worker
    model: medical
    stage: worker

spec:
  selector:
    app: medical-worker

  ports:
  - name: http
    protocol: TCP
    port: 8006
    targetPort: 8006

  type: ClusterIP
