apiVersion: v1
kind: Service

metadata:
  name: part1-service
  labels:
    app: part1

spec:
  selector:
    app: part1
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
